// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_3tuDXfue61L8jSsPlYCvo_YLAuPXzE',
    appId: '1:304662416451:web:df8f1325b6930fda2ed8f6',
    messagingSenderId: '304662416451',
    projectId: 'flutter-project-f2d44',
    authDomain: 'flutter-project-f2d44.firebaseapp.com',
    storageBucket: 'flutter-project-f2d44.appspot.com',
    measurementId: 'G-S1MHVR4SLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYlCg3Duj7w1WpgbrkPyKwjbo0dHrcY0',
    appId: '1:304662416451:android:ea2ae68a4556257f2ed8f6',
    messagingSenderId: '304662416451',
    projectId: 'flutter-project-f2d44',
    storageBucket: 'flutter-project-f2d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn91Ib7YognpznoQCAve1rjxqMQv2kgAU',
    appId: '1:304662416451:ios:9b81bae9384923302ed8f6',
    messagingSenderId: '304662416451',
    projectId: 'flutter-project-f2d44',
    storageBucket: 'flutter-project-f2d44.appspot.com',
    iosClientId: '304662416451-5j7f29ak8ha6kme0ndtd0caem9ql8cbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn91Ib7YognpznoQCAve1rjxqMQv2kgAU',
    appId: '1:304662416451:ios:9b81bae9384923302ed8f6',
    messagingSenderId: '304662416451',
    projectId: 'flutter-project-f2d44',
    storageBucket: 'flutter-project-f2d44.appspot.com',
    iosClientId: '304662416451-5j7f29ak8ha6kme0ndtd0caem9ql8cbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
